### ISSUE TITLE
May I ask if you can provide the original dataset

### ISSUE THREAD

**Issue by isCopyman** [alfonsogijon/WindTurbines_PINNs#1]

**Comment by alfonsogijon** [comment]
Thank you for your interest in our research. In response to your request, I regret to inform you that I am unable to share the original "La Haute Borne" dataset, as I do not have explicit permission from Engie to distribute it. I initially accessed this dataset through a public link approximately two years ago; however, this link now appears to be broken.

The only data available in my repository is a reduced version, which includes a limited set of variables and has undergone some preprocessing. You can access this subset at the following link: [https://github.com/alfonsogijon/WindTurbines_PINNs/tree/main/Dataset](https://urldefense.com/v3/__https://github.com/alfonsogijon/WindTurbines_PINNs/tree/main/Dataset__;!!D9dNQwwGXtA!Wxi6pJPnFC9Qa-pf3Q1NO9NTbeVluxHZ4fgiiLdkby_xM4AInIGMqV8enZMDDMiCOQk5yw7NQU-xTC0JMKRH$)

I hope this resource proves helpful, as it is the extent of what I am able to provide. You may consider contacting Engie directly if you wish to request access to the full dataset.

**Comment by isCopyman** [comment]
Thank you very much for your reply. I am also unable to access the complete data. I will try to contact Engie.
